### ISSUE TITLE
1.49 compatibility

### ISSUE THREAD

**Issue by vugi99** [Timmy-the-nobody/WebUI3d2d#4]
[2023-04-15 20:23:08] WARNING  Using deprecated 'Package.GetPath()' method! Please replace it with 'Package.GetName()'. 
	- [1] [webui3d2d/Client/Index.lua]:32: in main chunk

**Comment by Timmy-the-nobody** [comment]
Thanks for the report @vugi99 ! I'll push an update that fixes it

**Comment by Timmy-the-nobody** [comment]
Fixed in [1.5.0](https://github.com/Timmy-the-nobody/WebUI3d2d/releases/tag/v1.5.0)
